name: clubkompass
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  calendar_view: ^1.2.0
  provider: ^6.1.2
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/just_icon.png
    - assets/blogpost/
    - assets/profile/
    - assets/appimages/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/just_icon.png"
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/just_icon.png"
